user_details/config/routes.rb
Rails.application.routes.draw do

get "/user/new" => "users#new", :as => "user_new"
post "/user/new" => "users#create", :as => "user_create"

get "/users/list" => "users#index", :as => "user_list"

get "/user/:id/edit" => "users#edit", :as => "user_edit"

put "/user/:id/edit" => "users#update", :as => "user_update"

delete "/user/:id" =>"users#destroy", :as => "user_destroy"
get "/user/:id" => "users#profile", :as =>"user_profile"
get "/user/:id" => "users#show", :as =>"user_show"
get "/project/new" => "projects#new", :as => "project_new"
post "/project/new" => "projects#create", :as => "project_create"

get "/projects/list" => "projects#index", :as => "project_list"

end

user_details/app/models/profile.rb
class Profile < ActiveRecord::Base
	belongs_to :user
end

user_details/app/models/project.rb
class Project < ActiveRecord::Base
end

user_details/app/models/user.rb
class User < ActiveRecord::Base
   attr_accessor :password_encrypt
   before_save :encrypt_password

   def encrypt_password
   if true
     self.password = BCrypt::Engine.generate_salt
     self.password = BCrypt::Engine.hash_secret(password_encrypt, password)
   end
 end
 	validates :firstname,:lastname,presence: true
 	validates_presence_of :email, :message =>"should be unique"
 validates :password, :presence => true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{8,})\z/, message: "Not valid" }
end

user_details/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

user_details/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def new
		@project=User.new
end
def create

	@project=User.new(project_params)
	@project.save
end
def index
	@projects=Project.all
end
private
	def project_params
		params.require(:project).permit(:name,:duration,:teamsize,:cost,:domain)
end
end

user_details/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user=User.new
	end

	def create
		# binding.pry
		@user=User.new(user_params)
		
   if @user.save
     redirect_to user_list_path
   else
   render 'new'
   end
end

 def profile
   @user=User.find_by_id(params[:id])
 end

 def project
 end
 
 def show
  @user=User.find_by_id(params[:id])
  redirect_to user_profile_path
 end

	def index
		@users=User.all
end

def edit
	@user=User.find_by_id(params[:id])

end

def update
	@user=User.find_by_id(params[:id])
			@user.update_attributes(user_params)
			redirect_to user_list_path
	end

	def destroy
			@user=User.find_by_id(params[:id])
			@user.destroy
			redirect_to user_list_path
	end
	private
	def user_params
		params.require(:user).permit(:firstname,:lastname,:email,:password)
end
end

user_details/app/helpers/application_helper.rb
module ApplicationHelper
end

user_details/app/helpers/projects_helper.rb
module ProjectsHelper
end

user_details/app/helpers/users_helper.rb
module UsersHelper
# 	def show_errors(@user, :firstname)
#   if @user.errors.any?
#     if !@user.errors.messages[:firstname].blank?
#       @user.errors.messages[:firstname].join("FirstName cannot be blank")
#     end
#   end
# end 
end

user_details/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UserDetails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

user_details/app/views/projects/index.html.erb
<h1>User Details</h1>
<table border="2px">
    <tr>
        <td>Name</td>
        <td>Duration</td>
        <td>Teamsize</td>
         <td>cost</td>
        <td>Domian</td>
    </tr><% @projects.each do |u| %><br>
    <tr>
        <td><%= u.name %></td>
        <td><%= u.duration%></td>
        <td><%= u.teamsize %></td>
           <td><%= u.cost%></td>
        <td><%= u.domain %></td>
    
    </tr>
    <% end %>
</table>

user_details/app/views/projects/new.html.erb
<%= form_for :project do |u| %>
<p>
  <%= u.label :Name%><br>
  <%= u.text_field :name %>
  </p>

  <p>
  <%= u.label :Duration%><br>
  <%= u.text_field :duration %>
  </p>
  <p>
   <%= u.label :Teamsize %><br>
  <%= u.text_field :teamsize %>
  </p>

  <p>
   <%= u.label :Cost %><br>
  <%= u.text_field :cost %>
  </p>
  <p>
   <%= u.label :Domain %><br>
  <%= u.text_field :domain %>
  </p>
<p>
  <%= u.submit%>
  </p>
<% end %>

user_details/app/views/users/edit.html.erb
<%= form_for :user, url: user_edit_path(@user), method: :put do |u| %>
<p>
  <%= u.label :FirstName%><br>
  <%= u.text_field :firstname%>
  </p>

  <p>
  <%= u.label :LastName%><br>
  <%= u.text_field :lastname %>
  </p>
  <p>
   <%= u.label :Email %><br>
  <%= u.text_field :email %>
  </p>
<p>
  <%= u.submit%>
  </p>
<% end %>

user_details/app/views/users/index.html.erb
<h1>User Details</h1>
<table border="2px">
    <tr>
        <td>FirstName</td>
        <td>LastName</td>
        <td>Email</td>
    </tr><% @users.each do |u| %><br>
    <tr>
        <td><%= u.firstname %></td>
        <td><%= u.lastname %></td>
        <td><%= u.email %></td>
        <td><%= link_to 'Edit', user_edit_path(u) %></td>
        <td><%= link_to 'Destroy', user_destroy_path(u),
        method: :delete,
        data: {confirm: 'Are you sure?'} %></td>
       <td><%= link_to 'Projects', project_list_path(u) %></td>
    </tr>
    <% end %>
</table>

user_details/app/views/users/new.html.erb
<%= form_for :user do |u| %>
<% @user.errors.each do |attr, msg| %>
<%= "#{attr} #{msg}" if @user.errors[attr].first == msg %> 
<% end %>
<p>
  <%= u.label :FirstName%><br>
  <%= u.text_field :firstname %>
  </p>

  <p>
  <%= u.label :LastName%><br>
  <%= u.text_field :lastname %>
  </p>
  <p>
   <%= u.label :Email %><br>
  <%= u.text_field :email %>
  </p>

  <p>
   <%= u.label :Password %><br>
  <%= u.password_field :password %>
  </p>
<p>
  <%= u.submit%>
  </p>
<% end %>

user_details/app/views/users/profile.html.erb
<h1>Profile Details</h1>
<table border="2px">
    <tr>
        <td>FirstName</td>
        <td>LastName</td>
        <td>Email</td>
    </tr><br>
    <tr>
        <td><%= @user.firstname %></td>
        <td><%= @user.lastname %></td>
        <td><%= @user.email %></td>
        <td><%= link_to 'Edit and Update', user_edit_path(@user) %></td>
        
    </tr>
   
</table>